#!/bin/bash

generate_post_data()
{
  cat <<EOF
{
 "score": $WARNING_DIFF
}
EOF
}

CODING_BOYSCOUT_LOGGING=${CODING_BOYSCOUT_LOGGING:=0}
CODING_BOYSCOUT_MODE=${CODING_BOYSCOUT_MODE:='local'}

if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
then
	echo "runnig in $CODING_BOYSCOUT_MODE mode"
fi

FILES_TO_CHECK=`git diff --name-only --cached`

if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
then
	echo "checking files $FILES_TO_CHECK"
fi


WARNINGS_AFTER=`java -jar $CHECKSTYLE_JAR -c $CHECKSTYLE_FILE $FILES_TO_CHECK | wc -l`


if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
then
	echo "warnings if we commit this $WARNINGS_AFTER"
fi

STASH_SIZE_BEFORE=`git stash list | wc -l`
git stash > /dev/null
STASH_SIZE_AFTER=`git stash list | wc -l`

STASH_DIFF=$((STASH_SIZE_AFTER - STASH_SIZE_BEFORE))


WARNINGS_BEFORE=`java -jar $CHECKSTYLE_JAR -c $CHECKSTYLE_FILE $FILES_TO_CHECK | wc -l`
WARNING_DIFF=$((WARNINGS_AFTER - WARNINGS_BEFORE))



if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
then
	echo "difference in warnings is $WARNING_DIFF"
fi


if [ $STASH_DIFF -gt 0 ]
then
	if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
	then
	    echo "finished comparison unstash"
	fi
    git stash pop > /dev/null
    git add $FILES_TO_CHECK > /dev/null
else
    echo "nothing was stashed exit"
    exit 0
fi



if [ $WARNING_DIFF -gt 0 ]
then
    echo "oh noes this would add $WARNING_DIFF new warnings"
    java -jar $CHECKSTYLE_JAR -c $CHECKSTYLE_FILE ./
    exit 1
else
    if [ $WARNING_DIFF -eq 0 ]
    then
      echo "no new warnings, no warnings eliminated"
    else
        echo "nice, you eliminated $WARNING_DIFF warnings"

        if [ $CODING_BOYSCOUT_MODE = 'local' ]
        then
            if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
            then
            	echo "writing to commit_warnings file"
            fi
            echo "`git log --oneline | head -n1 | cut -d ' ' -f1` $WARNING_DIFF" >> commit_warnings
        else
            SERVER_ADDR="http://localhost:19283"
            SCOUT_NAME=`git config user.name`
            SCOUT_NAME=${SCOUT_NAME// /_}

            POST_ADDR="$SERVER_ADDR/api/v1/scout/$SCOUT_NAME/score"
            POST_BODY="{\"score\": $WARNING_DIFF}"

            if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
            then
                echo "messaging server $POST_ADDR with body $POST_BODY"
            fi

            POST_BODY='{"score": $WARNING_DIFF}'

            curl -H "Content-Type: application/json" -d "$(generate_post_data)" $POST_ADDR

            if [ $CODING_BOYSCOUT_LOGGING -gt 0 ]
            then
                echo "messaged server"
            fi
        fi
    fi
fi


